### ISSUE TITLE
DryRunner doesn't work if project directory contains spaces

### ISSUE THREAD

**Issue by drauch** [tgjones/dryrunner#11]
DryRunner isn't able to build the web project if the project directory contains a space. This is unfortunate, as the default VS2015 project directory contains spaces (`C:\Users\<username>\Documents\Visual Studio 2015\Projects`).

The first argument to msbuild must be quoted propertly, see TestSiteDeployer.Build() method, string.Format() call for ProcessStartInfo arguments.

**Comment by chrischu** [comment]
Should be fixed in v0.3.2.
