### ISSUE TITLE
TestSiteManager Fails When Project Has Macros

### ISSUE THREAD

**Issue by a11smiles** [tgjones/dryrunner#5]
My website project has macros in the pre-build and post-build events (i.e. $(SolutionDir), etc.)

When attempting to run the TestSiteManager, my build output window shows *Undefined* for each of the macros.

**Comment by a11smiles** [comment]
@tgjones I've modified your project (added two TestSiteOptions) to support MSBuild macros.  If you'd like, you can merge my fork.

**Comment by a11smiles** [comment]
@tgjones  I've also added the ability to specify additional/custom targets.  My web project was using pre- & post-build events that performed functions like dotless compilation and YUICompression.  Since the rendered files are not part of the project (they're rebuilt on every run), I needed a custom target in my project file that copied the resulting files to the test folder.

**Comment by tgjones** [comment]
That's great! Could you create a pull request (https://help.github.com/articles/creating-a-pull-request/) with these changes? I'd be happy to merge it.

**Comment by a11smiles** [comment]
So apparently your appveyor took 40 mins to compile the library?  Not sure, but as you can see from the diff comparison, I’ve only added a few properties to the library.  Looks like it may be an appveyor issue.

**Comment by tgjones** [comment]
I'm not sure what happened there - I've kicked off another build.

**Comment by tgjones** [comment]
The build got further than last time - but I just remembered that it has *never* worked on AppVeyor, presumably because the tests start an instance of IIS Express, and that doesn't work on AppVeyor. But no problem - I'll test this locally and then merge it.

**Comment by a11smiles** [comment]
Tim,

Any update on the build?

Thanks,
Joshua

**Comment by tgjones** [comment]
Fixed by #6.
