### ISSUE TITLE
DryRunner statically links an old version of MSBuild

### ISSUE THREAD

**Issue by chrischu** [tgjones/dryrunner#9]
Hi!

Today I noticed that DryRunner links the MSBuild dlls in version 4.0. This can be a problem, when projects using DryRunner want to use C# 6 features, since those need newer MSBuild versions (14.0).

The easiest way to fix this, would be to just link the new MSBuild version (and in the process also increase the framework version used by DryRunner to at least 4.5.1, otherwise the newer dlls cannot be referenced). However, that would make it necessary to build a new version of DryRunner for every MSBuild version (and maybe also maintain old ones).

It might be more feasible to circumvent the problem by calling MSBuild via the executable and make the executable path overridable. This solution would surely be more upfront work, because the code dealing with log redirection would need to be changed to work based on file or something like that, but in the end it would keep maintenance costs for new MSBuild versions low.

Maybe there is also some other (and better) solution I cannot think of right now :).

**Comment by tgjones** [comment]
Thanks for the clear write-up. I'm not actually using DryRunner myself anymore; I am keeping up-to-date with pull requests, but I'm not actively working on it myself. So I'll leave this open in case someone wants to contribute a fix. The latter solution - calling MSBuild via the executable - seems more future- (and past-) proof.

**Comment by chrischu** [comment]
This was actually fixed in v0.3.0.
